# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-03 11:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(default='aaa', max_length=20)),
                ('client_type', models.CharField(default='aaa', max_length=20)),
                ('active', models.IntegerField(default=1)),
                ('client_acronyms', models.CharField(default='false', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='undefined', max_length=30)),
                ('site_type', models.CharField(default='restaurant', max_length=20)),
                ('active', models.IntegerField(default=1)),
                ('aaa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_green_interface.Client')),
            ],
        ),
        migrations.CreateModel(
            name='SiteContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='aaa', max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(default='aaa', max_length=12)),
                ('bbb', models.ForeignKey(default=999, on_delete=django.db.models.deletion.CASCADE, to='smart_green_interface.Site')),
            ],
        ),
        migrations.CreateModel(
            name='SiteWorkingHoursDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default='0000-00-00')),
                ('time_from', models.TimeField(default='00:00:00')),
                ('time_to', models.TimeField(default='00:00:00')),
                ('bbb', models.ForeignKey(default=9999, on_delete=django.db.models.deletion.CASCADE, to='smart_green_interface.Site')),
            ],
        ),
    ]
