# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-03 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_green_interface', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='aaa',
            new_name='client_id',
        ),
        migrations.RenameField(
            model_name='sitecontact',
            old_name='bbb',
            new_name='site_id',
        ),
        migrations.RenameField(
            model_name='siteworkinghoursdetail',
            old_name='bbb',
            new_name='site_id',
        ),
        migrations.AlterField(
            model_name='site',
            name='site_name',
            field=models.IntegerField(default=99999),
        ),
    ]
