# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-03 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_green_interface', '0002_auto_20160803_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='site_number',
            field=models.IntegerField(default=99999),
        ),
        migrations.AlterField(
            model_name='site',
            name='site_name',
            field=models.CharField(default='undefined', max_length=20),
        ),
    ]
