# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-03 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_green_interface', '0003_auto_20160803_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='SgClientLinkage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sg_index', models.IntegerField(default=9999)),
                ('client_linkage', models.CharField(default='undefined', max_length=30)),
            ],
        ),
    ]
