# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-03 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_green_interface', '0004_sgclientlinkage'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteworkinghoursdetail',
            name='daily_manager',
            field=models.EmailField(default='aaa@aaa.com', max_length=254),
        ),
        migrations.AddField(
            model_name='siteworkinghoursdetail',
            name='daily_manager_phone',
            field=models.CharField(default='99999999999', max_length=12),
        ),
    ]
