# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-03 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_green_interface', '0005_auto_20160803_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontact',
            name='type',
            field=models.CharField(default='none', max_length=20),
        ),
    ]
