# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-03 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_green_interface', '0006_sitecontact_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitecontact',
            name='name',
        ),
        migrations.AlterField(
            model_name='sitecontact',
            name='email',
            field=models.EmailField(default='aaa@aaa.com', max_length=254),
        ),
    ]
