# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-07 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_green_interface', '0007_auto_20160803_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontact',
            name='password',
            field=models.CharField(default='1234567890', max_length=20),
        ),
    ]
