# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-07 12:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smart_green_interface', '0009_sitecontact_client_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitecontact',
            name='client_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_green_interface.Client'),
        ),
    ]
