# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-07 12:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smart_green_interface', '0010_auto_20160807_1537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitecontact',
            name='client_id',
        ),
    ]
