# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 06:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smart_green_interface', '0011_remove_sitecontact_client_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siteworkinghoursdetail',
            options={'ordering': ['-date']},
        ),
    ]
