# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 12:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smart_green_interface', '0012_auto_20160817_0639'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SgClientLinkage',
        ),
        migrations.RemoveField(
            model_name='siteworkinghoursdetail',
            name='site_id',
        ),
        migrations.DeleteModel(
            name='SiteWorkingHoursDetail',
        ),
    ]
